#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "requests",
# ]
# ///
"""
Sync community health files from pulp/governance repository.
"""

import sys
from pathlib import Path

import requests


GOVERNANCE_REPO = "pulp/governance"
GOVERNANCE_BRANCH = "main"
BASE_URL = f"https://raw.githubusercontent.com/{GOVERNANCE_REPO}/{GOVERNANCE_BRANCH}"


def noop(content: str) -> str:
    """No-op processor that returns content unchanged."""
    return content


def process_security_md(content: str) -> str:
    """Replace relative link in SECURITY.md with absolute link to governance repo."""
    replacement = (
        f"https://github.com/{GOVERNANCE_REPO}/blob/{GOVERNANCE_BRANCH}/"
        "docs/vulnerability-management-policy.md"
    )
    return content.replace("docs/vulnerability-management-policy.md", replacement)


FILES_TO_SYNC = {
    "SECURITY.md": process_security_md,
    "CODE_OF_CONDUCT.md": noop,
    "CONTRIBUTING.md": noop,
}

HEADER_TEMPLATE = """<!--
This file is synced from {source_url}
The source of truth is the pulp/governance repository.
Do not edit this file directly - changes should be made in pulp/governance.
-->

"""


def create_header(filename: str) -> str:
    """Create the header comment for synced files."""
    source_url = (
        f"https://github.com/{GOVERNANCE_REPO}/blob/{GOVERNANCE_BRANCH}/{filename}"
    )
    return HEADER_TEMPLATE.format(source_url=source_url)


def download_file(filename: str) -> str:
    url = f"{BASE_URL}/{filename}"
    response = requests.get(url)
    response.raise_for_status()
    return response.text


def sync_file(filename: str, processor, repo_root: Path) -> None:
    """Download and sync a single file."""
    print(f"Syncing {filename}...", end=" ")

    try:
        content = download_file(filename)
        content = processor(content)
        target_path = repo_root / filename
        final_content = create_header(filename) + content
        target_path.write_text(final_content)
    except requests.RequestException as e:
        print(f"✗ Failed to download: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"✗ Failed: {e}")
        sys.exit(1)
    print("✓")


def main() -> None:
    """Main entry point."""
    # Find repository root (assumes script is in .github/scripts/)
    script_path = Path(__file__).resolve()
    repo_root = script_path.parent.parent.parent

    print(f"Syncing files from {GOVERNANCE_REPO} to {repo_root}")
    print()

    for filename, processor in FILES_TO_SYNC.items():
        sync_file(filename, processor, repo_root)

    print()
    print("All files synced successfully!")


if __name__ == "__main__":
    main()
